development:
  adapter: postgresql
  encoding: unicode
  database: gallery
  pool: 5
  host: localhost
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: gallery_test
  pool: 5
  username: postgres
  password: password

production:
  url: <%= ENV['DATABASE_URL'] %> 